name: fetal_femur_ultrasound
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  http: ^1.1.0
  another_flushbar: ^1.12.30
  provider: ^6.0.5
  get: ^4.6.1
  syncfusion_flutter_datepicker: ^23.1.44
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/images/
    - lib/images/userprofile.jpg
  uses-material-design: true
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
